
const INSERT_OPEN_RESOURCE = 'INSERT_OPEN_RESOURCE';
const SET_CURRENT_OPEN = 'SET_CURRENT_OPEN';
const REMOVE_RESOURCE_OPEN = 'POP_RESOURCE_OPEN';

export {
  INSERT_OPEN_RESOURCE,
  SET_CURRENT_OPEN,
  REMOVE_RESOURCE_OPEN
}
